### ISSUE TITLE
Correct HTTP Status Code from Errors

### ISSUE THREAD

**Issue by marweck** [wearetheledger/fabric-node-chaincode-utils#16]
Hi all, thanks for sharing this library. It is very useful.

I was trying to send appropriate HTTP status codes for some errors in my smart contract chaincode.

Whenever I do `throw new NotFoundError('data.not.found');`, I get:

`
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "Error: transaction returned with failure: {\"name\":\"Error\",\"status\":500,\"message\":\"data.not.found\"}"
}
`

I get the same HTTP 500 error messages even when I use `new ChaincodeError('message', <any HTTP status>);`

What am I doing wrong?

**Comment by Superjo149** [comment]
The error messages have always been a little iffy, i'll look at it again.

**Comment by marweck** [comment]
Closing. Don't need it anymore. Thanks.
