### ISSUE TITLE
Issue running on HLF 1.3

### ISSUE THREAD

**Issue by wassimz** [wearetheledger/fabric-node-chaincode-utils#19]
I have tried to test the library on a modified version of fabcar example and deployed on HLF 1.3.
When calling a chaincode function using the _StubHelper.generateUUID_ method, I got the following issue:

>  message: 'this.stub.getTxTimestamp(...).toDate is not a function'

Any idea ??

**Comment by Superjo149** [comment]
What do you mean with "test"? test as in writing tests or trying out?

**Comment by wassimz** [comment]
What I mean I have install/instantiate a similar version of the provided [fabcar chaincode](https://github.com/wearetheledger/fabric-network-boilerplate) on fabric 1.3 and I got the error provided above when invoking a function (initLedger in my case) using the method StubHelper.generateUUID.

**Comment by SeriousAnt** [comment]
Running into the same issue with fabric v1.4 and fabric-node-chaincode-utils 4.0.1 when calling 

`stubHelper.getStub().getTxTimestamp().toDate()`

Working arround it with:

`new Date(stubHelper.getStub().getTxTimestamp().getSeconds() * 1000)`

Seems to be a problem with Timestamp to Date conversion

**Comment by Superjo149** [comment]
fixed in v4.0.3
